version: '3'
services:
  db:
    platform: linux/x86_64
    image: postgres:14.5
    container_name: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    container_name: api
    build: ./api
    ports:
        - 80:80
    restart: on-failure
    depends_on:
        - db
    environment:
      - POSTGRES_DSN=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://127.0.0.1/docs || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
